### ISSUE TITLE
Attributed text issue 

### ISSUE THREAD

**Issue by AnkitPanchal10** [simformsolutions/SSSpinnerButton#13]
when we set button text as attributed string, it's text shows in background at time of  spinner animation. 

[Uploading Screenshot at Oct 25 16-20-23.png…]()

**Comment by simformsolutions** [comment]
@AnkitPanchal10  Issue is Solved in new version 1.1.1

**Comment by simformsolutions** [comment]
@AnkitPanchal10  

Attributed text issue is resolved in new Release **version 1.1.1**
