### ISSUE TITLE
Spinner size customization

### ISSUE THREAD

**Issue by sanjaysinh-Chauhan** [simformsolutions/SSSpinnerButton#2]
## Enhancement wanted
I integrated this library. This library helps me a lot. I need some enhancement in this library.
Spinner size should be customized. 

![simulator screen shot - iphone 6s - 2018-06-13 at 19 59 31](https://user-images.githubusercontent.com/1305869/41357744-75d503b4-6f44-11e8-9e03-13005cb317ca.png)

In above Screenshot, spinner looks too big. I need to customize spinner width, height.###

**Comment by simformsolutions** [comment]
Now in new Version 1.0.3 You can custmise the size of spinner.
