### ISSUE TITLE
Tint Color issue when I stop animation

### ISSUE THREAD

**Issue by BhavikThummar** [simformsolutions/SSSpinnerButton#24]
It's showing blue color background while i stop animation.
You need to set tint color clear to resolve this issue.

![Simulator Screen Shot - iPhone 6s - 2019-04-17 at 11 18 05](https://user-images.githubusercontent.com/16632644/56264276-9559d780-6103-11e9-8e55-13ee208c9998.png)

**Comment by simformsolutions** [comment]
Hi, @BhavikThummar  this is not a tint color issue. We have added system button for test our SpinnerButton and for selelcted state its showing this. Just set button to custom type and try.
