### ISSUE TITLE
force back to normal state

### ISSUE THREAD

**Issue by fukemy** [simformsolutions/SSSpinnerButton#27]
hi. I am finding method to force button to normal when it's animating but the row is recycled

**Comment by fukemy** [comment]
@simformsolutions  can u help? Im using method 
`
btn?.stopAnimatingWithCompletionType(completionType: .fail, complete: nil)
`
to show error button, then display the alert in screen, once user click "OK" button, i need to force button back to normal state

**Comment by simformsolutions** [comment]
Hi @fukemy, Please check this method ` btn?.stopAnimationWithCompletionTypeAndBackToDefaults(completionType: .fail, backToDefaults: true, complete: nil)`
