### ISSUE TITLE
Layer issue in spinner.

### ISSUE THREAD

**Issue by sanjaysinh-Chauhan** [simformsolutions/SSSpinnerButton#3]
When start animation it works perfectly. But when stop animation spinner layer inside button removed after 0.5 sec of delay.

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/1305869/42223783-394f8d94-7ef6-11e8-9b7e-d9564075c644.gif)

**Comment by bhargavbajani** [comment]
@sanjaysinh-Chauhan 

Set/update image of spinner button in completion block of stopSpinner method.
Perform all next activity and All action from completion block.
